# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import typing

import numpy
import numpy.typing
import zarr.abc.store

@typing.final
class ChunkItem:
    def __new__(
        cls,
        key: builtins.str,
        chunk_subset: typing.Sequence[slice],
        chunk_shape: typing.Sequence[builtins.int],
        subset: typing.Sequence[slice],
        shape: typing.Sequence[builtins.int],
    ) -> ChunkItem:
        r"""
        `element_offsets` is always `None` here -- it is not a parameter, so this constructor cannot
        build a chunk-unit item. `ChunkItems::push_indices` builds those.
        """

@typing.final
class ChunkItems:
    r"""
    A batch of chunk items, built and held in Rust.

    Push one entry at a time, then pass the handle to
    `retrieve_chunk_items_and_apply_index`.
    """
    def __new__(cls) -> ChunkItems: ...
    def refuse_backwards(self, out_start: builtins.int) -> None:
        r"""
        Refuse an output start behind the last entry's end.

        `push_span`, `push_grid` and `push_points` each own one contiguous output range, so a
        start behind the cursor is two entries claiming the same bytes. `push_indices` does NOT
        call this -- see its doc comment: two bands of one read legitimately share an axis-0
        start, and disjointness for that one is proven downstream by `DisjointBytes`.
        """
    def push_indices(
        self,
        key: builtins.str,
        chunk_shape: typing.Sequence[builtins.int],
        shape: typing.Sequence[builtins.int],
        indices: numpy.typing.NDArray[numpy.int64],
        out_starts: typing.Sequence[builtins.int],
        out_widths: typing.Sequence[builtins.int],
        inner_shape: typing.Sequence[builtins.int],
        elem_starts: typing.Sequence[builtins.int] = [],
    ) -> None:
        r"""
        Build one batch entry's items and append them.

        `indices` select along AXIS 0 and are checked here: non-negative, non-decreasing, and
        inside the chunk extent.

        `out_starts` is NOT checked against entries already pushed. It was once -- see the
        comment in the body for why that check could not judge a banded entry and was removed.
        Disjointness is enforced downstream instead, by `DisjointBytes`, which vends every
        output range from a forward-only cursor and so cannot hand the same byte out twice.

        Axes after the first may be taken WHOLE or as one contiguous band, described by
        `out_starts`, `out_widths` and `elem_starts` -- so one selected index is still one
        contiguous run, and the rank-N case is the 1-D case with a run length.

        One obligation this CANNOT check: `shape` must be the real extent of the output buffer,
        since the output subset is bounded against it. A larger one describes bytes the buffer
        does not have, and that produces wrong data rather than an error.
        """
    def push_span(
        self,
        key: builtins.str,
        chunk_shape: typing.Sequence[builtins.int],
        shape: typing.Sequence[builtins.int],
        first: builtins.int,
        count: builtins.int,
        out_start: builtins.int,
        inner_extent: builtins.int,
    ) -> None:
        r"""
        Push a contiguous SPAN of the split axis, without naming its elements.

        `X[a:b]` and every whole-row read of a backed CSR arrive here. The elements are
        `first..first + count` on axis 0 with the trailing axes taken whole, which in row-major
        order is ONE contiguous block per inner chunk -- so each item needs a single coordinate
        and a run, not a coordinate per element.

        This is the whole point. Describing the span as elements instead -- `np.arange(a, b)`,
        on the grounds that a contiguous slice IS a sorted integer axis spelled differently --
        costs one `u64` per ELEMENT, built in numpy and walked one at a time here. Described as
        a run it is one coordinate and a length, whatever the span. The measurement behind that
        is in the commit message, not here: this doc comment is copied verbatim into
        `zarrs/_internal.pyi` by `pyo3-stub-gen`, so it is what `help()` shows a user, and
        milliseconds from a dataset they do not have belong in the history rather than in
        their terminal.
        """
    def push_grid(
        self,
        key: builtins.str,
        chunk_shape: typing.Sequence[builtins.int],
        shape: typing.Sequence[builtins.int],
        indices: numpy.typing.NDArray[numpy.int64],
        starts: numpy.typing.NDArray[numpy.uint64],
        run: builtins.int,
        out_start: builtins.int,
        inner_extent: builtins.int,
    ) -> None:
        r"""
        Push a GRID selection: the same columns taken from every selected index.

        `oindex[rows, cols]`, `X[:, cols]`, and any rank-N grid. Each selected index gives up
        the same sub-box, described as `starts.len()` runs of `run` elements -- because in
        row-major order a sub-box IS a set of runs. A fully scattered selection is `run == 1`.
        The runs land back to back in the output, so the item is still one output range.
        """
    def push_points(
        self,
        key: builtins.str,
        chunk_shape: typing.Sequence[builtins.int],
        shape: typing.Sequence[builtins.int],
        indices: numpy.typing.NDArray[numpy.int64],
        offsets: numpy.typing.NDArray[numpy.uint64],
        out_start: builtins.int,
        inner_extent: builtins.int,
    ) -> None:
        r"""
        Push a POINT selection: one element per index, each naming its own offset inside that
        index's elements.

        `X[rows, cols]` and `X[rows, 5]` both arrive as this -- zarr builds a
        `CoordinateIndexer` rather than dropping an axis -- and the ordinary route spends two
        allocations and a partial-decode call PER POINT. Grouping them by the chunk that gets
        decoded is the whole win, and it is the same grouping the row case uses: the output is
        flat, so `shape` is 1-D here while `chunk_shape` is not.
        """

@typing.final
class CodecPipelineImpl:
    @property
    def inner_chunk_shape(self) -> builtins.list[builtins.int] | None:
        r"""
        The innermost unit this array's codec chain decodes, or `None` to refuse the array.

        THREE ANSWERS, and Python needs all three: a shape is the inner chunk of a sharded
        array; an EMPTY shape means the array is not sharded, so its chunk is its own decode
        unit and only a batch entry knows that shape; `None` means this chain cannot be served
        at all -- a codec beside the sharding codec, which leaves the shard index addressing
        bytes that are no longer there.

        ASKED HERE RATHER THAN DERIVED TWICE. Python used to answer this itself by walking
        zarr's codec OBJECTS while `ShardInfo::from_codec_chain` answered it from the bound
        chain, and the two could disagree -- at which point Python built a description this
        side refuses, and the refusal surfaced as an uncaught `PyRuntimeError` from a call made
        outside `read`'s `try`, where the base pipeline would simply have read the array. A
        third-party codec registered for `sharding_indexed` reopens that gap however carefully
        the Python walk is written, because the two are answering from different data.

        It is also less code: the reach into `zarr.codecs.ShardingCodec`, `.chunk_shape` and
        `.codecs` goes away with it.
        """
    def __new__(
        cls,
        array_metadata: builtins.str,
        store_config: zarr.abc.store.Store,
        *,
        validate_checksums: builtins.bool = False,
        chunk_concurrent_minimum: builtins.int | None = None,
        chunk_concurrent_maximum: builtins.int | None = None,
        num_threads: builtins.int | None = None,
        direct_io: builtins.bool = False,
        file_handle_cache_size: builtins.int = 0,
        store_is_read_only: builtins.bool = False,
        read_pool_size: builtins.int | None = None,
        decode_pool_size: builtins.int | None = None,
        strict: builtins.bool = False,
    ) -> CodecPipelineImpl: ...
    def retrieve_chunk_items_and_apply_index(
        self,
        chunk_items: ChunkItems,
        value: numpy.typing.NDArray[typing.Any],
        max_row_reads_per_chunk: builtins.int | None = None,
    ) -> None:
        r"""
        The one read entry point.

        Takes a `ChunkItems` handle rather than a `Vec<ChunkItem>`: the vector costs one
        pyclass allocation per item on the way out of the builder and one extraction per item
        on the way in, where a handle costs one of each per call whatever the selection.

        There was a second entry point until 2026-08-30 -- a partial decoder per chunk over
        rayon, for selections this path declined. An audit of the public indexing surface found
        nothing reaching it, so it went, and a decline is now a fall back to zarr-python rather
        than a slower second Rust path.
        """
    def store_chunks_with_indices(
        self,
        chunk_descriptions: typing.Sequence[ChunkItem],
        value: numpy.typing.NDArray[typing.Any],
        write_empty_chunks: builtins.bool,
    ) -> None: ...

def pool_sizes() -> tuple[builtins.int | None, builtins.int | None]:
    r"""
    The sizes the two worker pools were BUILT with, or `None` where one has not been built.

    Pools are sized by the first read in the process, so a size set later is silently
    ignored. A benchmark that sets one and reports a number has to be able to say which of the
    two happened -- the repo's rule that a knob which was set is not a knob that arrived.
    """

def read_unit_stats() -> tuple[builtins.int, builtins.int]:
    r"""
    `(row, chunk)` jobs since the run began: rows read as their own byte range, against whole
    inner chunks read and decoded.

    Exposed so a test can assert the row path was TAKEN. Correctness cannot: both paths return
    the same values, so a gate that refuses everything passes every values test.
    """

def release_pools_for_fork() -> None:
    r"""
    Drop the two worker pools, so a `fork()` about to happen cannot inherit a held lock.

    Registered from Python with `os.register_at_fork(before=...)`. See
    [`read_decode::release_pools_for_fork`] for why the pid check inside `pools` is not enough
    on its own: it runs under the very lock that `fork` would copy as held.
    """

def shard_index_cache_stats() -> tuple[builtins.int, builtins.int, builtins.int]:
    r"""
    `(call_hits, array_hits, builds)` for the shard index cache, since the run began.

    A build is an index actually read and decoded; the two hit counts are the per-call cache
    and the per-array one, which are separate because the second only engages on a read-only
    store. Exposed so a test can assert the cache DID something -- correctness and timing both
    pass a cache that is never consulted.
    """
